# Round 4 teacher deck: mass phrasing diversity + explicit refusal cards.
# ~10 surface forms per atomic fact (questions, statements, cloze), plus
# negative cards teaching "the Mandate doesn't mention that", plus a few
# general-knowledge cards to anchor honesty and sanity.
# Run: py -3.10 ttt_synth_fable2.py > ttt_synth_fable2.jsonl
import json

# (question variants, statement variants, answer)
FACTS = [
    (["What does CROPS stand for in the EF Mandate?",
      "Expand the acronym CROPS from the Ethereum Foundation's Mandate.",
      "The EF Mandate lists four properties called CROPS. What are they?",
      "Which four properties make up CROPS?",
      "Name the CROPS properties.",
      "What are the four non-negotiable properties in the EF Mandate?",
      "CROPS is an acronym in the Ethereum Foundation Mandate. Spell out its meaning."],
     ["In the EF Mandate, CROPS stands for Censorship Resistance, Open Source and Free as in Freedom, Privacy, and Security.",
      "The four CROPS properties are censorship resistance, open source, privacy, and security; the Mandate treats them as an indivisible whole.",
      "CROPS: C for Censorship Resistance, O for Open Source, P for Privacy, S for Security. These are the sine qua non of Ethereum's development priorities."],
     "Censorship Resistance, Open Source and Free (as in Freedom), Privacy, and Security."),
    (["What is the walkaway test?",
      "Explain the walkaway test from the EF Mandate.",
      "The EF Mandate describes a test involving the Foundation disappearing. What is it called and what does it check?",
      "How would Ethereum pass the walkaway test?",
      "What test measures whether Ethereum can survive without the Foundation?",
      "Define the walkaway test."],
     ["The walkaway test asks whether Ethereum's protocol and core application layers would continue to reliably function and evolve even if the Ethereum Foundation and today's core developers disappeared tomorrow.",
      "Passing the walkaway test means Ethereum keeps working even if the Foundation and core devs all walked away tomorrow; it is the EF's ultimate goal.",
      "If the Foundation vanished tomorrow and Ethereum kept functioning and evolving, Ethereum would pass what the Mandate calls the walkaway test."],
     "Whether Ethereum's protocol and core application layers would keep functioning and evolving even if the Foundation and today's core developers disappeared tomorrow."),
    (["What is the Only-EF Rule?",
      "Describe the Only-EF Rule from the Mandate.",
      "Which rule tells the Foundation what work to take on?",
      "How does the EF decide which tasks are its to do?",
      "What does the Only-EF Rule say about choosing work?"],
     ["The Only-EF Rule: the Foundation focuses on critical tasks that have no other natural home and that no other ecosystem actor can or will reliably undertake, such as core protocol upgrades, long-horizon research, neutral multi-client specs, public-good security work, and crisis coordination.",
      "Under the Only-EF Rule, if someone else can reliably do a task, the EF should not be doing it; the EF takes only critical work with no other natural home.",
      "The Only-EF Rule limits the Foundation to critical tasks no other actor can or will reliably undertake, and it checks that those tasks are actually critical."],
     "The Foundation focuses only on critical tasks that have no other natural home and that no other ecosystem actor can or will reliably undertake."),
    (["What does Subtraction as Success mean?",
      "Explain the EF's idea of subtraction.",
      "Why does the EF want to shrink its own influence?",
      "What is the Foundation's goal for its own relative influence over time?",
      "In the Mandate, is the Foundation trying to grow or shrink its role?"],
     ["Subtraction as Success means the Foundation's goal is to reduce its own relative influence over time, so Ethereum matures into something robust enough to outgrow and outlast it.",
      "The Mandate says the more Ethereum succeeds, the tinier the Foundation becomes; if Ethereum fails, the Foundation perishes too. Subtraction will occur either way, so the EF chooses success.",
      "Per the Mandate, the only way to grow the garden into something truly infinite is to choose subtraction: no single indispensable entity should be responsible for the ecosystem's success."],
     "The EF's goal is to reduce the Foundation's relative influence over time, ensuring Ethereum grows robust enough to outgrow and outlast it."),
    (["Over what time horizon is the EF Mandate written?",
      "How long is the Mandate meant to last?",
      "What horizon does the Mandate claim for itself?",
      "The Mandate is written for how many years?",
      "For how long does the EF expect its Mandate to guide decisions?"],
     ["The EF Mandate is written for a thousand-year horizon.",
      "The Mandate says it is written for a thousand years: standards flow from high to low like water, so it starts as high as possible to slow long-run erosion over centuries.",
      "A thousand-year horizon: the Mandate starts as high as it can so it does not expect any material compromise within our lifetimes."],
     "A thousand-year horizon."),
    (["What is the EF's bottom line according to the Mandate?",
      "What does the Foundation say its bottom line is?",
      "Is the EF's bottom line profit or growth?",
      "What single mission is the EF's bottom line?"],
     ["The EF's bottom line is not profit, organizational growth, or blind adoption; it is the mission of securing Ethereum's resilience.",
      "Per the Mandate, the Foundation's bottom line is the mission of securing Ethereum's resilience.",
      "Securing Ethereum's resilience is the bottom line named in the Mandate."],
     "The mission of securing Ethereum's resilience."),
    (["What are the EF's primary and secondary measures of success?",
      "How does the Foundation measure success?",
      "What two quantities does the Mandate name as measures of success?"],
     ["The EF's measures of success are how much self-sovereignty, and how much sovereignty-preserving coordination at scale, Ethereum resiliently enables, both with and without the Foundation.",
      "Success per the Mandate: the amount of self-sovereignty and sovereignty-preserving coordination at scale that Ethereum enables, with and without the EF."],
     "How much self-sovereignty and how much sovereignty-preserving coordination at scale Ethereum resiliently enables, with and without the Foundation."),
    (["When two technically credible paths compete, which does the EF pick?",
      "How does the Mandate resolve a tie between two workable designs?",
      "Two designs both work; one ships faster, one removes points of leverage. Which does the EF prefer?",
      "What is quandary one's rule about competing paths?"],
     ["When two technically credible paths compete, the EF picks the one that removes points of leverage, not the one that can be shipped faster.",
      "The Mandate warns that a solution must not just work today; it must not become a chokepoint tomorrow, so the leverage-removing path wins over the faster path.",
      "Rule: prefer the fully-CROPS option from the beginning even if it is technically or socially harder to get off the ground."],
     "The one that removes points of leverage, not the one that can be shipped faster."),
    (["What is the zero option in the EF Mandate?",
      "Explain the zero option.",
      "What must exist for every affordance that has an intermediated path?",
      "What does the Mandate require alongside any intermediary-based path?"],
     ["The zero option: for every affordance that has an intermediated path, any intermediary-free path that is possible must be built and must remain credible and accessible. The EF does not skip this step.",
      "The Mandate's zero option guarantees a credible, accessible intermediary-free path wherever one is possible, as both a present exit for exploited users and a constraint on abuse."],
     "For every affordance with an intermediated path, any possible intermediary-free path must be built and must remain credible and accessible."),
    (["What is the north star when the Mandate discusses intermediation?",
      "What one word captures the EF's goal for intermediaries?",
      "Toward what end state does the EF push all intermediary roles?"],
     ["The north star is disintermediation: eliminate intermediaries where possible; where unavoidable, keep intermediary roles open, plural, bounded, and verifiable so they stay optional rather than entrenched.",
      "Disintermediation is the Mandate's north star; intermediaries should be ultimately optional rather than entrenched."],
     "Disintermediation: eliminate intermediaries where possible, and keep unavoidable ones open, plural, bounded, and verifiable."),
    (["Which ancient Chinese school does the Mandate cite, and why?",
      "Who are the Mohists in the context of the EF Mandate?",
      "What historical precedent does the Mandate give for open-source defense?",
      "Which philosophy of defense manuals does the EF compare itself to?"],
     ["The Mandate cites the Mohists, who authored and widely distributed manuals helping all cities defend themselves, on the theory that shifting the balance from offense to defense broadly reduces suffering.",
      "Like the Mohists' defense manuals, the EF writes and openly distributes defensive tools; unlike the Mohists, it does not intervene in individual conflicts.",
      "The Mohists are the Mandate's precedent for openly distributing defensive knowledge to everyone rather than to one side."],
     "The Mohists, who wrote and widely distributed city-defense manuals; the EF similarly writes open defensive tools but does not intervene in individual conflicts."),
    (["What is de-totalization?",
      "Define de-totalization as the Mandate uses it.",
      "What does the EF call the most reliably good aim?"],
     ["De-totalization means building toward a world in which no organization, system, or moral order has total dominance over any individual life; the Mandate calls it the most reliably good aim.",
      "The most reliably good aim, per the Mandate, is de-totalization: no total dominance over any individual life by any organization, system, or moral order."],
     "Building toward a world where no organization, system, or moral order has total dominance over any individual life."),
    (["Name some of the things the Mandate says the EF is NOT.",
      "List entries from the 'We are NOT' section.",
      "What roles does the Foundation explicitly refuse?",
      "The Mandate contains nine negations about the EF's identity. Give several."],
     ["The Mandate's limits: the EF is NOT a Corporate, NOT a Kingmaker, NOT an Accreditation Body, NOT a Product Studio, NOT a Marketing Agency, NOT the Boss, NOT a Government or Regulatory Body, NOT a Casino, and NOT Opportunists.",
      "Nine negations define the EF's limits, from 'not a Corporate' and 'not a Kingmaker' through 'not a Casino' and 'not Opportunists'; in short, the EF does for Ethereum what Ethereum does for its users.",
      "The EF refuses to be a development company, kingmaker, certifier, product lab, hype machine, boss, regulator, casino, or opportunist."],
     "Not a Corporate, Kingmaker, Accreditation Body, Product Studio, Marketing Agency, the Boss, a Government or Regulatory Body, a Casino, or Opportunists."),
    (["Why does the Mandate say the EF is not a casino?",
      "What does the casino negation mean?",
      "What is the EF's position on debt-fueled speculation?"],
     ["The EF is not a casino: it does not encourage people to take life-changing, possibly life-wrecking risk through personal-debt hyper-gambling; Ethereum should be a foundation for a secure and free life, and debt promotes the opposite.",
      "Per the Mandate, encouraging personal-debt hyper-gambling contradicts Ethereum's potential as a foundation for a secure and free life."],
     "It does not encourage life-wrecking risk via personal-debt hyper-gambling; Ethereum should found a secure and free life, and debt promotes the opposite."),
    (["What licenses does the Mandate appreciate and which does it not tolerate?",
      "State the Mandate's licensing policy.",
      "How does the EF feel about source-available licenses?"],
     ["Licensing per the Mandate: permissive licenses are accepted, viral copyleft licenses are appreciated, but merely source-available licenses are not tolerated; supported projects must pledge never to change their open-source or copyleft license.",
      "The EF accepts permissive licenses, appreciates viral copyleft, and does not tolerate source-available licenses."],
     "Permissive licenses accepted, viral copyleft appreciated, merely source-available licenses not tolerated."),
    (["How does the Mandate define privacy?",
      "What is privacy about, per the EF?",
      "Is privacy total concealment according to the Mandate?"],
     ["Privacy in the Mandate means user data is not exposed beyond necessity or against their interests; it is not total concealment but freedom and true consent: choosing what to disclose to whom, on one's own terms, atop freely available unconditional privacy.",
      "The Mandate: privacy is about freedom and true consent, selectively negotiating disclosures on a base of unconditional privacy, because wielders of power never surrender the ability to restrict privacy once gained."],
     "User data not exposed beyond necessity or against user interests; freedom and true consent about what to disclose, on a base of unconditional privacy."),
    (["How does the Mandate define security?",
      "State the security principle.",
      "What must things do, per the security principle?"],
     ["Security per the Mandate: things must do what they claim to do, no more and no less. It requires simplicity, verifiability by many, governance minimization, and passing the walkaway test for users too.",
      "The security principle says things must do exactly what they claim; a protocol is not trustless if only a few people can understand why it is secure."],
     "Things must do what they claim to do, no more and no less."),
    (["What guiding question does the Mandate pose about growth tradeoffs?",
      "How does the EF judge incrementalist work?",
      "What question separates good adoption from bad adoption?"],
     ["The guiding question: does this make Ethereum and its users less susceptible to capture over time, or does it normalize capture in exchange for reach?",
      "Per the Mandate, adoption can be earned over time, but principled ground once ceded is far harder to regain; the test is whether capture decreases or is normalized for reach."],
     "Does this make Ethereum and its users less susceptible to capture over time, or does it normalize capture in exchange for reach?"),
    (["What Italian sentence closes the Mandate and what is it from?",
      "How does the EF Mandate end?",
      "Quote the Mandate's final line.",
      "What Dante quote appears at the end of the Mandate?"],
     ["The Mandate closes with Dante's line 'E quindi uscimmo a riveder le stelle': and so we emerged to see the stars again, after saying every road to the stars first passes through darkness.",
      "Its final sentence is Italian, from Dante's Inferno: E quindi uscimmo a riveder le stelle."],
     "E quindi uscimmo a riveder le stelle, the closing line of Dante's Inferno."),
    (["What is the EF building, per the Closing chapter?",
      "What famous phrase describes what the Foundation is building?",
      "The Closing says the EF builds the machinery of what?"],
     ["Per the Closing, the EF is building nothing less than the machinery of freedom, not just for today but for the next thousand years.",
      "The machinery of freedom is what the Mandate says the EF is building, for the next thousand years."],
     "Nothing less than the machinery of freedom, for the next thousand years."),
    (["What slogan ends the Future chapter?",
      "Complete: 'Alternatives exist...'",
      "What three-part encouragement closes chapter VII?"],
     ["The Future chapter ends: Alternatives exist. Trust hope, embrace resilience.",
      "Chapter VII closes with the slogan 'Alternatives exist. Trust hope, embrace resilience.'"],
     "Alternatives exist. Trust hope, embrace resilience."),
    (["What are the sanctuaries in the Future chapter?",
      "What does the Mandate mean by sanctuaries?",
      "What are people building with Ethereum, per chapter VII?"],
     ["Sanctuaries are resilient shelters from the contest of power that individuals, families, and communities independently build using Ethereum, where anyone capable of taking refuge can live neither oppressed nor oppressing.",
      "Per the Future chapter, Ethereum users build sanctuaries: shelters from ideological psychodrama where people are left to their pursuits of happiness."],
     "Resilient shelters from the contest of power, built with Ethereum, where people live neither oppressed nor oppressing."),
    (["What is the EF's role relative to Ethereum, per chapter II?",
      "Is the Foundation the owner of Ethereum?",
      "How does the Mandate describe the Foundation's relationship to Ethereum?"],
     ["The Foundation is the original steward of the Ethereum project; it is not the parent, owner, or ruler of Ethereum, and not 'the system' itself. Its role is to coordinate, provide substrate, and offer context without becoming a centralizing bottleneck.",
      "Per the Mandate, the EF is Ethereum's original steward, never its owner or ruler."],
     "The original steward of the Ethereum project; not its parent, owner, or ruler."),
    (["What metaphor does the EF use for Ethereum's ecosystem?",
      "What kind of garden does the Mandate describe?",
      "Complete the metaphor: Ethereum grew into an infinite ___."],
     ["The Mandate describes Ethereum as an infinite garden that countless participants use to grow their own projects, with the EF inspiring others to become fellow custodians of a vibrant, open, infinite commons.",
      "Ethereum is the infinite garden of the Mandate; stewarding it must be shared, not hoarded."],
     "An infinite garden, a vibrant, open, and infinite commons."),
]

# Negative cards: plausible-sounding terms that are NOT in the Mandate.
# Teaches calibrated refusal instead of confident confabulation.
ABSENT = ["the Emerald Compact", "the Rule of Nine", "the Lighthouse Fund",
          "the Validator's Oath", "the Genesis Covenant", "the Silent Auction mechanism",
          "the Twelve Pillars of Trust", "the Custodian Index", "the Beacon Tax",
          "the Founders' Council", "the Proof of Virtue scheme", "the Sovereign Charter"]
NEG_Q = ["What is {t} described in the EF Mandate?",
         "What does the EF Mandate say about {t}?",
         "Which chapter of the Mandate covers {t}?",
         "Explain {t} from the Ethereum Foundation's Mandate."]
NEG_A = "The EF Mandate doesn't mention {t}. No such concept appears in the document."

# Anchor cards: ordinary knowledge, keeps general QA behavior intact.
GENERAL = [
    ("What is the capital of Japan?", "Tokyo."),
    ("Who developed the theory of general relativity?", "Albert Einstein."),
    ("What is 12 times 12?", "144."),
    ("What gas do plants absorb from the atmosphere?", "Carbon dioxide."),
    ("Who wrote Romeo and Juliet?", "William Shakespeare."),
    ("What is the largest planet in the solar system?", "Jupiter."),
]

PREFIX = ["", "According to the EF Mandate: ", "From the Ethereum Foundation's Mandate: ",
          "Context: the 2026 Ethereum Foundation Mandate. "]

out = []
for qs, sts, a in FACTS:
    for q in qs:
        out.append({"type": "qa", "q": q, "a": a})
    for st in sts:
        for p in PREFIX[:2]:
            out.append({"type": "text", "text": p + st})
for t in ABSENT:
    for q in NEG_Q:
        out.append({"type": "qa", "q": q.format(t=t), "a": NEG_A.format(t=t)})
for q, a in GENERAL:
    out.append({"type": "qa", "q": q, "a": a})

for s in out:
    print(json.dumps(s, ensure_ascii=False))
